In [1]:
import pandas as pd
import numpy as np

#Carregando csv de pedidos
df_orders = pd.read_csv("../data/staging/orders.csv", encoding="UTF-8")

display(df_orders.sample(10))

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
28915,4974295376c45fc743638ffad01b8959,1b1db207b5fcfb3102a1899c38c9a9fd,delivered,2018-07-21 17:51:16,2018-07-21 18:04:09,2018-07-23 14:40:00,2018-08-01 20:24:37,2018-08-10
79460,200e0548bbc2cbdcafa92e6c5ab73fb6,21866995bb1dd2c15eea9269bfa0a8dd,delivered,2017-08-02 10:20:00,2017-08-02 22:23:33,2017-08-16 19:10:15,2017-08-24 14:57:35,2017-09-11
59443,cd5343ffb012a7157ddbcf5720100c01,c6ae270b58b4692321a73aa741d183af,delivered,2018-08-26 12:38:57,2018-08-26 12:50:18,2018-08-27 14:18:00,2018-08-30 14:38:54,2018-09-11
83696,f1e21bf02dd5a9f69c64397ef7bd0433,298c879e4fc0844be75e87e613246470,delivered,2018-03-19 11:20:11,2018-03-19 11:31:39,2018-03-19 21:08:51,2018-03-20 21:48:41,2018-03-29
18070,fe5cf33c8006e3a98776622acb39c9fe,f0d9d8e4ac3a29ef1b3382939e006298,delivered,2018-01-11 11:31:42,2018-01-11 11:38:50,2018-01-15 17:24:47,2018-01-26 17:59:02,2018-02-06
6849,02d273267575a29864f552b2de598580,fb6895f16f2b933e56af615dbcecf0aa,delivered,2018-05-28 17:31:20,2018-05-28 17:55:50,2018-05-30 07:59:00,2018-06-13 15:04:52,2018-06-29
7760,0d2d1445891e7aba669fa2069d695601,739ee2d2d5960609ad780937fd9fa282,delivered,2017-10-09 19:54:18,2017-10-11 03:49:33,2017-10-11 18:28:36,2017-10-16 16:46:59,2017-10-26
49961,7a36fa82d4bcff7d936c10be470b9c8e,bfebb91e718433a55143ee450423c983,delivered,2016-10-05 23:14:34,2016-10-07 03:12:09,2016-10-14 23:21:27,2016-10-19 20:57:33,2016-12-05
98917,d0e379ef6e0ea864c470893dbd5da4dd,39d7c7a5e9c2172c16234017faf854ba,delivered,2018-03-11 19:07:43,2018-03-12 19:09:38,2018-03-15 18:49:35,2018-03-16 20:03:37,2018-03-22
89279,7ec1c103b7dc4cf5213a0a3956b28a6d,7a2b2664f27252530d93dbbe1895a107,delivered,2017-06-23 18:38:34,2017-06-23 18:50:14,2017-06-28 14:45:54,2017-07-04 15:06:28,2017-07-06

In [2]:
#Análise Inicial dos dados
print("Quantidade de colunas - ")

display(df_orders.shape)
display(list(df_orders.columns))
columns = list(df_orders.columns)

print("Descrição das tabelas - ")

display(df_orders.info())
display(df_orders.describe())
print("Soma dos valores NULL de cada coluna - ")
display(df_orders.isnull().sum())
print("Soma dos valores NAN de cada coluna - ")
display(df_orders.isna().sum())

print("Soma dos valores duplicados -")

display(df_orders.duplicated().sum())
print("Categorias da coluna status - ")
display(df_orders['order_status'].unique())

Quantidade de colunas -

(99441, 8)

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

Descrição das tabelas -
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

None

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20
freq,1,1,96478,3,9,47,3,522

Soma dos valores NULL de cada coluna -

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Soma dos valores NAN de cada coluna -

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Soma dos valores duplicados -

np.int64(0)

Categorias da coluna status -

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [3]:
#Limpeza dos dados
print("Colunas de datas - ")
display(df_orders)
print("Convertendo tipos das colunas - ")
df_orders['order_purchase_timestamp'] = pd.to_datetime(df_orders['order_purchase_timestamp'], format="%Y-%m-%d %H:%M:%S")
df_orders['order_approved_at'] = pd.to_datetime(df_orders['order_approved_at'], format="%Y-%m-%d %H:%M:%S")
df_orders['order_delivered_carrier_date'] = pd.to_datetime(df_orders['order_delivered_carrier_date'], format="%Y-%m-%d %H:%M:%S")
df_orders['order_delivered_customer_date'] = pd.to_datetime(df_orders['order_delivered_customer_date'], format="%Y-%m-%d %H:%M:%S")
df_orders['order_estimated_delivery_date'] = pd.to_datetime(df_orders['order_estimated_delivery_date'], format="%Y-%m-%d")
df_orders['order_status'] = df_orders['order_status'].str.strip()
df_orders['order_status'] = df_orders['order_status'].str.title()
order_status_categories = list(df_orders['order_status'].unique())
display(df_orders.info())

Colunas de datas -

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03

Convertendo tipos das colunas -
<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

None

In [4]:
print("Analisando a coluna order_approved_at - ")
print("Status dos pedidos com data de aprovação nula - ")

for status in order_status_categories:
    quantity = df_orders.loc[(df_orders['order_approved_at'].isnull()) & (df_orders['order_status'] == status)].shape[0]
    if(quantity > 0):
        print(status)
        display(quantity)

#Provavelmente faz parte da regra de negócio deixar colunas de datas nulas quando o status referente permite

Analisando a coluna order_approved_at -
Status dos pedidos com data de aprovação nula -
Delivered

14

Canceled

141

Created

5

In [5]:
df_orders.to_csv("../data/processed/orders_processed.csv", index=False)